// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	user "lendra/features/user"

	mock "github.com/stretchr/testify/mock"
)

// UserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type UserServiceInterface struct {
	mock.Mock
}

// AdminCreateUser provides a mock function with given fields: userId, input
func (_m *UserServiceInterface) AdminCreateUser(userId int, input user.User) error {
	ret := _m.Called(userId, input)

	if len(ret) == 0 {
		panic("no return value specified for AdminCreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, user.User) error); ok {
		r0 = rf(userId, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AdminGetAllUser provides a mock function with given fields: userId
func (_m *UserServiceInterface) AdminGetAllUser(userId int) ([]user.User, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for AdminGetAllUser")
	}

	var r0 []user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) ([]user.User, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) []user.User); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangePassword provides a mock function with given fields: userId, oldPassword, newPassword
func (_m *UserServiceInterface) ChangePassword(userId int, oldPassword string, newPassword string) error {
	ret := _m.Called(userId, oldPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string, string) error); ok {
		r0 = rf(userId, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: input
func (_m *UserServiceInterface) Create(input user.User) error {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(user.User) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: userId
func (_m *UserServiceInterface) Delete(userId int) error {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetById provides a mock function with given fields: userId
func (_m *UserServiceInterface) GetById(userId int) (*user.User, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (*user.User, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(int) *user.User); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: email, password
func (_m *UserServiceInterface) Login(email string, password string) (*user.User, error) {
	ret := _m.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*user.User, error)); ok {
		return rf(email, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *user.User); ok {
		r0 = rf(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: userId, input
func (_m *UserServiceInterface) Update(userId int, input user.UserUpdate) error {
	ret := _m.Called(userId, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, user.UserUpdate) error); ok {
		r0 = rf(userId, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserServiceInterface creates a new instance of UserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceInterface {
	mock := &UserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
